name: Maclean
options:
  bundleIdPrefix: com.geekaz
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "26.1"
  generateEmptyDirectories: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.geekaz.maclean
    PRODUCT_NAME: Maclean
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_STRICT_CONCURRENCY: complete
    CODE_SIGN_ENTITLEMENTS: Maclean/Resources/Maclean.entitlements
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
schemes:
  Maclean:
    build:
      targets:
        Maclean: all
    run:
      config: Debug
targets:
  Maclean:
    type: application
    platform: macOS
    sources:
      - path: Maclean
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        ENABLE_HARDENED_RUNTIME: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: Maclean
    entitlements:
      path: Maclean/Resources/Maclean.entitlements
      properties: {}
